set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0



set-option -g mouse off
set -g mode-keys vi

bind r source-file ~/.tmux.conf \\; display-message "~/.tmux.conf reloaded"

# Unbind the default prefix (Ctrl+b)
unbind C-b

# Set prefix to Ctrl+j
set -g status-style 'bg=#333333 fg=#5eacd3'
set-option -g prefix C-j
set -g base-index 1

bind C-j send-prefix
# Use reattach-to-user-namespace to access system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "sh -c '. ~/.dotfiles/shellrc && copy'"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
   
# Splits
bind | split-window -h
bind - split-window -v
